[package]
name = "syncplay"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
audiotags = "0.4.1"
kdam = "0.3.0"
serde = "1.0.163"
toml = "0.7.3"
config = "0.13.1"
